name = "PlasmaEquilibriumToolkit"
uuid = "57ef8d28-8191-49ce-8cf8-17f9379aac88"
authors = ["Benjamin Faber <bfaber@wisc.edu>",
           "Aaron Bader <abder@wisc.edu>"]
version = "0.5.4"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
CoordinateTransformations = "0.5, 0.6"
Documenter = "0.25, 0.26, 0.27"
Interpolations = "0.10.1, 0.11, 0.12, 0.13"
LabelledArrays = "1.3"
Polyester = "0.5, 0.6"
StaticArrays = "1"
StructArrays = "0.4.4, 0.5, 0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
